services:
  main-database:
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:10000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: event-space
    restart: unless-stopped
    volumes:
      - main-database:/var/lib/postgresql/data
  security-service:
    image: thejustrusik/event-space-security-service:latest
    environment:
      DB_HOST: main-database
      DB_PORT: 5432
      DB_NAME: event-space
      DB_USERNAME: user
      DB_PASSWORD: user
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "10001:8080"
    restart: unless-stopped
  order-service:
    image: karakatalmasova/event-space-order-service:latest
    environment:
      DB_HOST: main-database
      DB_PORT: 5432
      DB_NAME: event-space
      DB_USERNAME: user
      DB_PASSWORD: user
    volumes:
      - ${STORAGE_DIR}:/app/upload-dir/
    ports:
      - "10002:8080"
    restart: unless-stopped
  front-admin:
    image: thejustrusik/event-space-fron-admin:develop
    ports:
      - "9999:80"
    restart: unless-stopped
  front-main:
    image: thejustrusik/event-space-front-main:develop
    ports:
      - "9998:80"
    restart: unless-stopped
volumes:
  main-database:
